# Generated by Django 5.0.1 on 2024-02-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cadastro_options_cadastro_adicionado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['id'], 'verbose_name_plural': 'cadastros'},
        ),
    ]
