# Generated by Django 5.0.1 on 2024-02-10 21:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cadastro_alterado_por_cadastro_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='endereço',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
