# Generated by Django 5.0.1 on 2024-02-11 01:20

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cadastro_endereço_alter_cadastro_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='alterado',
            new_name='alterado_em',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='adicionado',
            new_name='criado_em',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
