# Generated by Django 5.0.1 on 2024-02-11 01:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_alterado_cadastro_alterado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
