# Generated by Django 5.0.1 on 2024-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_produto',
            field=models.FloatField(),
        ),
    ]
